### ISSUE TITLE
Why use Python for customize?

### ISSUE THREAD

**Issue by TofPlay** [dduan/DistributionTests#2]
Hi 
Interesting tool 🙂
Why do you use Python? 😰
Why do not you use Swift as a scripting language? 😉

Take a look at these articles/videos: 
* [Scripting in Swift is Pretty Awesome](https://goo.gl/OiQ8xI)
* [A Beginner’s Guide to Scripting in Swift](https://goo.gl/uylJNa)
* [Swift script all the things!](https://goo.gl/lgA3uZ)
* [Scriptarian: Swift scripting for macOS?](https://goo.gl/EzziRD)

Tool:
* [Scriptarian - Scripting Studio for macOS](https://goo.gl/9vPu8E)

**Comment by dduan** [comment]
I will when I get a chance. Great suggestion!
